### ISSUE TITLE
Direct image filters

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/docs#377] opened 2015-09-21 20:38 UTC
I've removed this,

https://github.com/CartoDB/docs/commit/10e2b428a9d83e1d04c791ddeefc1d43d938f7c3

will it ever work in CartoDB, or should it work? @javisantana

**Comment by csobier** [comment] 2015-09-25 18:43
@andrewxhill , is `direct-image filters`not working because it is a bug, or by design?  (We removed from the docs, CartoCSS parameters, for the time being).

I need to know if I should add this issue to a future milestone if they are going to support this?  (Ditto for the other items we removed... I know product is working on one of them, i.e. `background-color`; they should link the issue to docs when the code is implemented)

**Comment by andrewxhill** [comment] 2015-09-25 19:41
@javisantana

**Comment by andrewxhill** [comment] 2015-09-25 19:41
or maybe @rochoa

**Comment by csobier** [comment] 2015-09-29 16:56
ping

**Comment by csobier** [comment] 2015-09-30 12:01
Assigning to the next milestone, hopefully we'll get an answer before the next release???

**Comment by fdansv** [comment] 2015-10-05 13:55
To the best of my knowledge, we're not supporting this anywhere and there are no plans of doing so. `image-filters` in torque, however, are applied directly to the whole canvas, so bear in mind that in a small part of our carto usage, `image filters` behaves as `direct-image-filters`. This however doesn't mean we should use it, so to me deleting it from the reference is fine.

**Comment by csobier** [comment] 2015-10-05 13:58
`direct-image-filters` already removed from the CartoCSS doc. I am closing this issue, as there are no plans to support this. Thank you!

**Closed by csobier** 2015-10-05 13:58 UTC
Labels: CartoCSS
