### ISSUE TITLE
JSFiddles linked from CartoDB docu don't show anything

### ISSUE THREAD

**Issue by xavijam** [CartoDB/docs#384] opened 2015-09-24 10:05 UTC
Hi,

I was trying to show some colleagues how to use CartoDB.js with the JSFiddle examples I used some time ago to learn, and they don't seem to work anymore. This is the doc site that links to them, and this is the list of links that once showed some data, but don't anymore:

http://jsfiddle.net/gh/get/library/pure/CartoDB/academy/tree/master/t/03-cartodbjs-ground-up/lesson-2/jsfiddle_demo_ondone
http://jsfiddle.net/gh/get/library/pure/CartoDB/academy/tree/master/t/03-cartodbjs-ground-up/lesson-2/jsfiddle_demo_multilayer
Maybe something on the documentation user has changed. The vis.json looks OK to me, but nothing is being plotted.

Cheers,
@raquel-ucl

**Comment by matallo** [comment] 2015-09-24 10:08
hey @raquel-ucl they are working for me, can you give us some more info on the errors that would appear in the developer tools?

If you don't mind I'm closing the issue, but feel free to comment so we will try to find the cause

Cheers!

**Comment by raquel-ucl** [comment] 2015-09-24 10:15
Hey there.

Gosh, you are so quick! 
I've tried from my computer and my colleague's with Safari and Chrome. 
These are the errors from the Dev Tools:

```
Failed to load resource: the server responded with a status of 404 (Not Found)

(index):42 Uncaught ReferenceError: cartodb is not defined

http://jsfiddle.net/css//css/light.css?update_06092015 Failed to load resource: the server responded with a status of 404 (Not Found)
```

Hope this helps! And apologies if it's me doing something wrong 0:-)

**Comment by matallo** [comment] 2015-09-24 10:17
Uhm, I'll reopen again for investigating further and come back hopefully with an answer, thanks for sharing!

**Comment by raquel-ucl** [comment] 2015-09-24 10:58
This is a bit off, but I've just realised if I remove the alert sentences from the examples, the links work.

**Comment by csobier** [comment] 2015-10-06 14:14
I cannot reproduce this behavior, it works for me too. I'm glad you were able to figure out a workaround so that you can use the examples in your environment! I will close this issue but certainly let us know if we can do anything else for you.

**Closed by csobier** 2015-10-06 14:14 UTC
Labels: bug
